### ISSUE TITLE
How can I get started with custom dataset?

### ISSUE THREAD

**Issue by dsgh2** [Jongchan/attention-module#20]
When I tried, below error occurred.

Traceback (most recent call last):
  File "train.py", line 310, in <module>
    main()
  File "train.py", line 149, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "train.py", line 193, in train
    losses.update(loss.data[0], input.size(0))
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

Is there anyone who tried to train with own custom dataset?

**Comment by thinkInJava33** [comment]
losses.update(loss.data[0], input.size(0))->losses.update(loss.item(),input.size(0))

**Comment by sakurasakura1996** [comment]
> When I tried, below error occurred.
> 
> Traceback (most recent call last):
> File "train.py", line 310, in 
> main()
> File "train.py", line 149, in main
> train(train_loader, model, criterion, optimizer, epoch)
> File "train.py", line 193, in train
> losses.update(loss.data[0], input.size(0))
> IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
> 
> Is there anyone who tried to train with own custom dataset?

Do you successed to train custom dataset with this code? Where to get the pretrained model? expect your reply
